services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-network

  python-app:
    image: python:3.12-slim
    container_name: python-container
    working_dir: /app
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: ["/bin/bash", "./run.sh"]
    depends_on:
      - mysql
    environment:
      DB_HOST: ${MYSQL_SERVER}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
